apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    deployment: "{{ .Values.prodServices.labels.deployment }}"
  name: "{{ .Values.prodServices.labels.deployment }}"
spec:
  host: "{{ .Values.prodServices.host }}.{{ .Values.prodServices.domain }}"
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: "{{ .Values.prodServices.labels.deployment }}"
