{{ with .Values.prodServices }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .fullname }}
  labels:
    deployment: {{ .labels.deployment }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    deployment: {{ .labels.deployment }}
{{ end }}      
