apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    deployment: web
  name: myweb2
spec:
  host: myweb2.apps.ocp4.example.com
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: myweb
