# Default values for multi-container-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

webServices:
  replicaCount: 1
    #  image: "registry.access.redhat.com/ubi9/httpd-24:latest"
  image: "quay.io/ravindra_be2004/mydemo:v1"
  nameOverride: ""
  fullnameOverride: ""
  fullname: "myweb"
  host: "myweb1"
  domain: "apps.ocp4.example.com"
  labels:
    - app: web
  selectorLabels:
    - app: web
  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: false
    className: ""
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
     
dbServices:
replicaCount: 1

  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
